# Generated by Django 2.2.6 on 2019-11-10 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_cursos_grade_curricular_repositorios_sistemas'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursos',
            name='grade',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Grade_curricular'),
        ),
        migrations.AddField(
            model_name='cursos',
            name='usuario',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='disciplinas',
            name='grades',
            field=models.ManyToManyField(to='api.Grade_curricular'),
        ),
        migrations.AddField(
            model_name='disciplinas',
            name='usuarios',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
