# Generated by Django 2.2.6 on 2019-11-10 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20191110_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade_curricular',
            name='codigo',
        ),
        migrations.AddField(
            model_name='grade_curricular',
            name='carga_horario',
            field=models.BigIntegerField(null=True),
        ),
    ]
