# Generated by Django 2.2.6 on 2019-11-10 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20191110_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade_curricular',
            name='nome',
        ),
    ]
