# Generated by Django 2.2.6 on 2019-11-13 00:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_remove_grade_curricular_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplinas',
            name='usuarios',
        ),
        migrations.AddField(
            model_name='disciplinas',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
