# Generated by Django 2.2.6 on 2019-11-17 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20191116_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Grade_curricular', unique=True),
        ),
    ]
